notifications:
  email: false
git:
  quiet: true
  depth: false
language: node_js
node_js: lts/*
#services:
#  - xvfb
python: 3.7
addons:
  apt:
    update: false
    packages:
      - curl
      - python3-pip
#      - libappindicator1
#      - fonts-liberation
#      - google-chrome-stable
install: true
before_install:
  #  - |
  #    export CHROME_BIN=/usr/bin/google-chrome
  #    export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash
    stop_any 3000 5000
  - |
    export PATH=$HOME/.local/bin:$PATH
    pip3 install --user --upgrade pip setuptools
    pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      name: starter
      env:
        - SUB_PROJECT=starter
      before_script:
        - cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm i -E
        - cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm start
        - cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm run logs &
        - wait_for 5000
      script: http :5000
      after_script: cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm stop
    - stage: deploy
      name: GitHub Pages
      env:
        - secure: "smZGafZl2zNs6ubxsI+Faf9AJhd/KQ+LvJYIYAWi9W2LH1/7PwFSTIvTEvVj03Y4g6CHm6B1vlaxK03LFJl3SZJ3GD7W7qf5cjO5Xhiea4cvY2ATlL4bln4yjHE1IVAGVhcLkBsofEVuOcMKlxyeV9Ku1ExOXScnkrMNbxMWuQwtaf44W2kpL1cNNfDUZ+VmBjwEkFIE3JcX8ootFMPWKINWr8kdeUsF1ouDdaYPENRBbkvrn6IhuBcuEBOhbvZNVIxw47QUKIN8vbfxfpE7pFc6OkKJG+KeRXmicHBRiT7lhYuDFIHy58hlBtdDbwzQKvDB5srPy56FeGSby4XKW0pVGQzAOTcUBeYMBBn9bzC63Bnu8qvf0YlhcllclW148CVVxdRLZde1IOEmh9O0cEwM2TLWyzMzodLQeFPzv5E6ceou/GSarl2/TItaTBth5moGuHq5LHRBsiw3FtXeB/glisuK1kqT3aityJJVhZEaoUrcbU7CyWcHUoR9ke7BIomgHDIUgNvo5qD7UCRkSSs7Lv13Ru8I0W3CofrjR3FiNmLg8QMv+i4fQI5ju7MQbXcfLxByQLZQhbVlpkvOkzm7AMsRnZu23j0ivaLJ4PdPcYfM7iuUf4GOg3/ecyWwhGjslGJa8oztPUt29l0SJ2UJTTHuEzfsEaIdxwso0Xs="
        - SUB_PROJECT=stylus-flex
      script: skip
      before_deploy:
        - set -e
        - cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm i -E
        - cd $TRAVIS_BUILD_DIR/$SUB_PROJECT && npm run gh
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: $TRAVIS_BUILD_DIR/$SUB_PROJECT/public
        target_branch: gh-pages
        on:
          branch: master
          condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  npm: true
  pip: true
  packages: true
  directories:
    - ~/.n*
    - ~/.local/daggerok
